### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by ilyar** [ccampbell/chromephp#14]
Uncaught TypeError: Cannot call method 'addEventListener' of undefined
(anonymous function)chrome-extension://homgcnaoacgigpkkljjjekpignblkeae/main.js:25
(anonymous function)chrome-extension://homgcnaoacgigpkkljjjekpignblkeae/main.js:34

**Comment by ccampbell** [comment]
This bug should be in https://github.com/ccampbell/chromephp-extension/issues since it is a javascript error.

That being said I think this is another extension you have installed causing issues.. If you look at the files for my extension I do not have a main.js.

That extension you are seeing the error with is https://chrome.google.com/webstore/detail/homgcnaoacgigpkkljjjekpignblkeae

**Comment by ilyar** [comment]
thank you
