### ISSUE TITLE
arrays displayed as objects

### ISSUE THREAD

**Issue by llbbl** [ccampbell/chromephp#19]
when I var_dump the variable is an array, but I dump it to ChromePhp it says it is an object. 

anyone notice this?

**Comment by ccampbell** [comment]
This is because PHP arrays can be arrays or hash tables.  If you log `ChromePhp::log(array(1, 2, 3));` I believe it will show up in the console as `[1, 2, 3]` (an array), but if you log `ChromePhp::log(array('test' => 1);` It will show up as an object because in Javascript this is an object/dictionary.

**Comment by ccampbell** [comment]
Closing this out since it is not a bug.
