### ISSUE TITLE
PHP Error: Recursion detected

### ISSUE THREAD

**Issue by bluetidepro** [ccampbell/chromephp#25]
I always get this PHP error when using the script on my site...

``` php
A PHP Error was encountered
Severity: Warning
Message: json_encode(): recursion detected
Filename: libraries/ChromePhp.php
Line Number: 396
```

Is there a fix for this?

**Comment by Rolilink** [comment]
+1 its happening to me too

**Comment by hakre** [comment]
The fix is the warning you see. A recursion has been detected. It makes no sense to fully json encode recursive structures as otherwise next to duplicate information this would kill the process with out of memory or stackspace.

Luckily recursions are detected! So you get a warning instead of a **crash**.

And yes, as long as there is recursion (and it _luckily_ is detected), you will see this little warning. So it will happen to everybody who will try to json_encode structures that contain recursion. The warning tells you so that you know about. How useful!

**Comment by bluetidepro** [comment]
@hakre Makes sense, thanks for the reply! :)
