### ISSUE TITLE
Browser crash because of a lot of cookies

### ISSUE THREAD

**Issue by qfox** [ccampbell/chromephp#6]
In _writeToFile after

<pre>
        file_put_contents($this->getSetting(self::LOG_PATH) . '/' . $file_name, $json);
</pre>

put that or something like that:

<pre>
        static $setCookie;
        if (empty($setCookie)) {
            $data = array(
                'uri' => $this->getSetting(self::URL_PATH) . '/' . $file_name,
                'request_uri' => $_SERVER['REQUEST_URI'],
                'time' => $this->_timestamp,
                'version' => self::VERSION
            );

            $setCookie = $this->_setCookie($data);
        }

        return $setCookie;
    }
</pre>

If not browser throws an error: "Error 325 (net::ERR_RESPONSE_HEADERS_TOO_BIG): Unknown error." and dont show a page.

**Comment by ccampbell** [comment]
I'm aware of this issue but it is not a simple fix.  I'm assuming you are using ChromePHP in file mode (ChromePhp::useFile()) because otherwise it will never get to _writeToFile.  

The particular cookie you mentioned is used to tell the client some information about the request, but in file mode that array is ALL that is written out to a cookie so it is very unlikely that will put you over the browser limit.

If you are using regular logging mode then it is much more likely, but there are checks in place to prevent it.  If you have a lot of other cookies/headers already being sent on your page then it is more likely to happen, but for that reason there is a configurable paramater:

self::MAX_TRANSFER => 3000

When the cookie bytes that needs to be written reaches 3000 bytes by default it stops.  You can try experimenting with this number to make it work better for your specific case.

ChromePhp::getInstance()->addSetting(self::MAX_TRANSFER, 1000);   or something lower.

**Comment by qfox** [comment]
Its not personal trouble, its Chrome cookie limit. I can easily remove from code ChromePHP, but its not a solution. I tell you about a real bug: file name writing to cookies each logging time (not one!). Why I must limit max transfer (whats it?) to 1000? Its a ugly hack.
Try to logout 5000 records to Chrome and youll see a bug. And look and cookies. 5000 identical record. Why? I don't know.
