### ISSUE TITLE
Support FirePHP protocol?

### ISSUE THREAD

**Issue by fuzzy76** [ccampbell/chromephp#9]
Is there a reason you opted to create your own protocol? If not, I hope you would consider making the extension FirePHP compatible.

**Comment by ccampbell** [comment]
Hi,

There are a number of reasons I opted to use my own.  The main reason is because Chrome Extensions do not support receiving headers which is what FirePHP protocol is based around.  Due to this limitation I am forced to use cookies to transmit data which brings up a whole series of other problems.  

Cookie sizes are limited so I wanted to be able to write the data in a stream and keep track of how much has been logged to prevent it from going over the cookie size limitations.  I wanted to compress/shrink down the data as much as possible in order to avoid hitting cookie size limits.  Also in order to support ajax requests I needed to be able to write out some data to a cookie, have the extension read it and then throw the data away to continue logging new data within the same request.  The Chrome extension listens for cookie change events.

Due to the cookie limitations I also offer support for writing data to a file which is then accessed to log it to the console.  I suppose it would have been possible to try to keep the data in the same format that FirePHP uses but I wanted to be able to easily update it and tie the updates between the extension and the server side library together.

If you are looking supporting both you can easily write a Console wrapper.  I have one that is available for my php framework.  https://github.com/ccampbell/sonic-extensions/tree/master/console.

**Comment by cweiske** [comment]
According to http://productforums.google.com/forum/#!topic/chrome/1u7DQv-ag_4 it should be possible to retrieve page headers when the user changes some settings.

**Comment by fuzzy76** [comment]
There is nothing in that topic that indicates that extensions can read the request headers. But there is, as far as I can tell, an API for doing that at http://code.google.com/chrome/extensions/webRequest.html

**Comment by ccampbell** [comment]
When I first wrote the extension Chrome did not support reading headers on requests for extensions.  In fact it wasn't added until Chrome 17 I believe.  The extension uses that now:

https://github.com/ccampbell/chromephp-extension/commit/0a60a237f4714325271c67a995a52653e2ff51df

But I still do not plan to change it to read FirePHP headers.  There are other extensions for Chrome that can do that already.
